config/routes.rb
RedditClone::Application.routes.draw do
  resources :users
  resources :subs do
    resources :links, only: [:new]
  end
  resources :links, except: [:new]
  resource :session

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  link_id           :integer          not null
#  parent_comment_id :integer
#  body              :string(255)      not null
#  created_at        :datetime
#  updated_at        :datetime
#

class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :user_id, presence: true
  validates :link_id, presence: true

  belongs_to :user
  belongs_to :link
  belongs_to :parent_comment, class_name: "Comment"
  has_many :daughter_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id


end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  body       :string(255)
#  url        :string(255)      not null
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true

  belongs_to :user
  has_many :link_subs
  has_many :subs, through: :link_subs
  has_many :comments

  def comments_by_parent_id
    return @comments_hash if @comments_hash
    comments_hash = Hash.new { |h,k| h[k] = [] }
    self.comments.each do |comment|
      comments_hash[comment.parent_comment_id] << comment
    end
    @comments_hash = comments_hash
  end
end

app/models/link_sub.rb
# == Schema Information
#
# Table name: link_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer
#  link_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class LinkSub < ActiveRecord::Base
  belongs_to :link
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :moderator_id, presence: true

  belongs_to :moderator, class_name: "User"
  has_many :link_subs
  has_many :links, through: :link_subs, inverse_of: :subs
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  email           :string(255)
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  before_validation :set_session_token

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :subs, foreign_key: :moderator_id, inverse_of: :moderator
  has_many :links

  attr_accessor :password

  def set_session_token
    self.session_token = self.class.generate_session_token
  end

  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save
    self.session_token
  end

  def password=(unencrypted_password)
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password).to_s
  end

  def is_password?(unencrypted_password)
     BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(user_params)
    user = User.find_by(username: user_params[:username])
    return user if user && user.is_password?(user_params[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    @link = Link.find(params[:id])
    # @comments = @link.comments
  end

  def new
    @sub = Sub.find(params[:sub_id])
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.user = current_user
    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render "new"
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render "edit"
    end
  end

  private
  def link_params
    params.require(:link).permit(:title, :url, :body, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(user_params)
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render "new"
    end
  end

  def destroy
    logout!
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
    5.times do
      @sub.links.build
    end
  end

  def create
    @sub = current_user.subs.new(name: params[:sub][:name])
    @sub.links.new(links_params)
    current_user.links << @sub.links
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      (5 - @sub.links.length).times { @sub.links.build }
      render "new"
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(name: params[:sub][:name])
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render "edit"
    end
  end

  private
  def links_params
    params.permit(links: [:title, :url, :body])
          .require(:links)
          .values
          .reject { |data| data.values.all?(&:blank?) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden'
      value=#{form_authenticity_token}
      name='authenticity_token'>".html_safe
  end

  def authenticate
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token
  end

  def logout!
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
    <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  Logged in as: <%= current_user.username %>
  <%= button_to "Log Out", session_path, method: :delete %>
<% else %>
  <%= link_to "Log In", new_session_path %>
  <%= link_to "Sign Up", new_user_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<%= render "layouts/errors" %>

<form action="<%= link_url(@link) %>" method="post" accept-charset="utf-8">
  <%= auth_token %>

  <input type="hidden" name="_method" value="PATCH">

  <br>
  <label for="link"> Title</label><input type="text" name="link[title]" value="<%= @link.title %>" id="link">
  <br>
  <label for="linkurl">URL</label><input type="text" name="link[url]" value="<%= @link.url %>" id="linkurl">
  <br>

  <label for="linkbody">Text</label><input type="text" name="link[body]" value="<%= @link.body %>" id="linkbody">
  <br>

  <input type="hidden" name="link[sub_ids][]" value="" >

  <% Sub.all.each do |sub| %>
    <label> <%= sub.name %>
      <input type="checkbox"
        name="link[sub_ids][]"
        value="<%= sub.id %>"
        id="some_name"
        <%= "checked" if @link.subs.include?(sub) %>><br>
    </label>
  <% end %>

  <p><input type="submit" value="Update Link"></p>
</form>

app/views/links/new.html.erb
<%= render "layouts/errors" %>

<form action="<%= links_url %>" method="post" accept-charset="utf-8">
  <%= auth_token %>

  <br>
  <label for="link"> Title</label><input type="text" name="link[title]" value="<%= @link.title %>" id="link">
  <br>
  <label for="linkurl">URL</label><input type="text" name="link[url]" value="<%= @link.url %>" id="linkurl">
  <br>

  <label for="linkbody">Text</label><input type="text" name="link[body]" value="<%= @link.body %>" id="linkbody">
  <br>

  <input type="hidden" name="link[sub_ids][]" value="" >

  <% Sub.all.each do |sub| %>
    <label> <%= sub.name %>
      <input type="checkbox"
        name="link[sub_ids][]"
        value="<%=sub.id %>"
        id="some_name"
        <%= "checked" if @sub == sub %>><br>
    </label>
  <% end %>

  <p><input type="submit" value="Create Link"></p>
</form>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>
<%= @link.url %><br>
<%= @link.body %><br>

<h3>Subs:</h3>
<% @link.subs.each do |sub| %>
  <%= link_to sub.name, sub_url(sub) %><br>
<% end %>

<%= link_to "Edit Link", edit_link_url(@link) %>
<%= link_to "Back to Links", links_url %>

app/views/subs/edit.html.erb
<%= render "layouts/errors" %>

<form action="<%= sub_url(@sub) %>" method="post" accept-charset="utf-8">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH" id="_method">

  <label for="name">Name</label><input type="text" name="sub[name]" value="<%= @sub.name %>" id="name">
  <br>
  <p><input type="submit" value="Update Sub"></p>
</form>

app/views/subs/index.html.erb
<h1> Welcome to Subs </h1>

app/views/subs/new.html.erb
<%= render "layouts/errors" %>

<form action="<%= subs_url %>" method="post" accept-charset="utf-8">
  <%= auth_token %>
  <label for="name">Name</label><input type="text" name="sub[name]" value="<%= @sub.name %>" id="name">

  <% @sub.links.each_with_index do |link, i| %>
  <h3> Link <%= i + 1 %> </h3>
  <br>
  <label for="link<%= i %>title"> Title</label><input type="text" name="links[<%= i %>][title]" value="<%= link.title %>" id="link<%= i %>title">
  <br>
  <label for="link<%= i %>url">URL</label><input type="text" name="links[<%= i %>][url]" value="<%= link.url %>" id="link<%= i %>url">
  <br>

  <label for="link<%= i %>body">Text</label><input type="text" name="links[<%= i %>][body]" value="<%= link.body %>" id="link<%= i %>body">
  <br>
  <% end %>
  <p><input type="submit" value="Create Sub"></p>
</form>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<%= link_to "Submit a Link", new_sub_link_url(@sub) %>

<% @sub.links.each do |link| %>
<hr>
  <h3>
    <%= link_to link.title, link_url(link) %>
  </h3>
  <%= link.url %><br>
  <%= link.body %>
</hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up </h1>

<%= render "layouts/errors" %>

<form action="<%= users_url %>" method="post" accept-charset="utf-8">

  <%= auth_token %>

  <label for="username">Username</label>
  <input type="text" name="user[username]" value="" id="username">

  <label for="email">Email</label>
  <input type="text" name="email" value="" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="" id="password">


  <p><input type="submit" value="Sign Up"></p>
</form>